# Azure AI Services Configuration
# Generated automatically by Terraform deployment
# Do not edit this file manually - it will be overwritten

# Azure AI Services (Language/Text Analytics)
AZURE_AI_SERVICES_ENDPOINT=${ai_services_endpoint}
AZURE_AI_SERVICES_KEY=${ai_services_key}

# Azure Key Vault
AZURE_KEY_VAULT_URI=${key_vault_uri}

# Azure Storage
AZURE_STORAGE_CONNECTION_STRING=${storage_connection}

# Azure Resource Information
AZURE_RESOURCE_GROUP=${resource_group}
AZURE_AI_FOUNDRY_ID=${ai_foundry_id}
AZURE_AI_FOUNDRY_PROJECT_ID=${ai_foundry_project_id}

# Environment
ENVIRONMENT=development

# For backward compatibility with existing code
ENDPOINT=${ai_services_endpoint}
KEY=${ai_services_key}